"""initial schema

Revision ID: 184a0cce8697
Revises:
Create Date: 2026-01-19 17:38:24.175724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '184a0cce8697'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_id', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('webhook_secret', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config_cache', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config_cache_updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('platform', 'platform_id')
    )
    op.create_index('idx_repositories_platform', 'repositories', ['platform'], unique=False)
    op.create_index('idx_repositories_active', 'repositories', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_table('jobs',
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('platform_pr_id', sa.String(length=255), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('head_sha', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('job_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'head_sha')
    )
    op.create_index('idx_jobs_status', 'jobs', ['status'], unique=False)
    op.create_index('idx_jobs_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('idx_jobs_priority', 'jobs', ['priority'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_table('reviews',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('pr_title', sa.Text(), nullable=False),
    sa.Column('pr_author', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('total_findings', sa.Integer(), nullable=False),
    sa.Column('blocker_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('info_count', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(length=100), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('llm_tokens_used', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('idx_reviews_pr_number', 'reviews', ['pr_number'], unique=False)
    op.create_index('idx_reviews_created_at', 'reviews', ['created_at'], unique=False)
    op.create_index('idx_reviews_total_findings', 'reviews', ['total_findings'], unique=False)
    op.create_table('findings',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('platform_comment_id', sa.String(length=255), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_findings_severity', 'findings', ['severity'], unique=False)
    op.create_index('idx_findings_file_path', 'findings', ['file_path'], unique=False)
    op.create_index('idx_findings_pipeline', 'findings', ['pipeline_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_findings_pipeline', table_name='findings')
    op.drop_index('idx_findings_file_path', table_name='findings')
    op.drop_index('idx_findings_severity', table_name='findings')
    op.drop_index('idx_reviews_total_findings', table_name='reviews')
    op.drop_index('idx_reviews_created_at', table_name='reviews')
    op.drop_index('idx_reviews_pr_number', table_name='reviews')
    op.drop_index('idx_jobs_priority', table_name='jobs')
    op.drop_index('idx_jobs_created_at', table_name='jobs')
    op.drop_index('idx_jobs_status', table_name='jobs')
    op.drop_index('idx_repositories_active', table_name='repositories')
    op.drop_index('idx_repositories_platform', table_name='repositories')
    op.drop_table('findings')
    op.drop_table('reviews')
    op.drop_table('jobs')
    op.drop_table('repositories')
    # ### end Alembic commands ###
